Dev
Akrid782/mcart_flutter_base pull request #1
Opened 2021-11-12 10:50 UTC by Akrid782

Тут готовая google лаба 1 и 2, и начата задние 1 с сеткой из квадратов

2021-11-12 10:57 UTC, artem-zaitsev requested changes
Небольшие правки с отступами.

2021-11-12 10:57 UTC, artem-zaitsev commented on lib/page/code_lab.dart
> +      MaterialPageRoute(builder: (context) {
лучше такие роуты в будущем выносить отдельно - иначе смешивается верстка двух отдельных экранов.

2021-11-12 10:57 UTC, artem-zaitsev commented on lib/page/code_lab.dart
> +          if (i.isOdd) {
еще можно сделать ListView.separated

2021-11-12 10:57 UTC, artem-zaitsev commented on lib/page/square.dart
> +                  margin: const EdgeInsets.all(marge),
У тебя получилось расстояние между двумя квадратами = 20. По дизайну 10. 
Лучше использовать просто SizedBox с заданным значением для пространства между квадратами.

2021-11-15 05:57 UTC, Akrid782 commented on lib/page/code_lab.dart
> +      MaterialPageRoute(builder: (context) {
Хорошо, я так понимаю выводить в отдельный виджет, нужно?

2021-11-15 05:58 UTC, Akrid782 commented on lib/page/square.dart
> +                  margin: const EdgeInsets.all(marge),
Поправил

2021-11-15 09:05 UTC, artem-zaitsev approved these changes
Мелкие помарки, их можно будет взять на вооружение на будущее. Сейчас править не стоит. 
Делай асинхронщину, буду ждать отдельный ПР по ней!
Это можешь сливать.

2021-11-15 19:02 UTC, Akrid782 commented on lib/page/list_page.dart
> +  List<Color> generationList() {
Поправил

2021-11-15 19:02 UTC, Akrid782 commented on lib/page/square.dart
> +      child: Container(
Хорошо, дальше буду писать правильно

2021-11-15 19:03 UTC, merged