Асинхронное взаимодействие
Akrid782/mcart_flutter_base pull request #3
Opened 2021-11-18 06:37 UTC by Akrid782

2021-11-18 08:50 UTC, artem-zaitsev requested changes
маленькие моменты, в остальном все довольно круто!
sync - async можно не править, это скорее просто пометил)

2021-11-18 08:50 UTC, artem-zaitsev commented on lib/main.dart
> +import 'package:base/page/sync.dart';
скорее async

2021-11-18 08:50 UTC, artem-zaitsev commented on lib/page/sync.dart
> +class SyncRequest extends StatefulWidget {
Async

2021-11-18 08:50 UTC, artem-zaitsev commented on lib/page/sync.dart
> +      _photos.addAll(parsePhotos(response.body));
parse лучше вынести из setState - операция может быть тяжелой, выполнять ее прям перед билдом - не лучший вариант.

В setState -  только изменение состояния.

2021-11-18 08:50 UTC, artem-zaitsev commented on lib/page/sync.dart
> +  Widget _buildContentListView(Photos _photo) {
Данный функционал лучше вынести в отдельный виджет.

В целом, принято выносить в приватные виджеты(или не приватные если их используют разные классы), чем делать buildSomething-методы. 

Это более рационально с точки зрения внутренних механизмов отрисовки фреймворка, и взаимодействия с InheritedWidget

2021-11-18 08:50 UTC, artem-zaitsev commented on lib/page/sync.dart
> +          if ((i + 1) >= _photos.length) {
сейчас запрос происходит только на предпоследнем жлементе, при быстром скролле - может быть задержка.

Чаще делают запрос на к примеру середине страницы, чтобы сгладить подлагивания из-за загрузки.

2021-11-19 06:14 UTC, Akrid782 commented on lib/page/sync.dart
> +          if ((i + 1) >= _photos.length) {
Поправил

2021-11-19 06:15 UTC, Akrid782 commented on lib/page/sync.dart
> +  Widget _buildContentListView(Photos _photo) {
Вынес в отдельный виджет

2021-11-19 06:15 UTC, Akrid782 commented on lib/page/sync.dart
> +      _photos.addAll(parsePhotos(response.body));
Поправил, вынес парсер за пределы setState

2021-11-19 06:15 UTC, Akrid782 commented on lib/page/sync.dart
> +class SyncRequest extends StatefulWidget {
Поправил

2021-11-19 06:16 UTC, Akrid782 commented on lib/main.dart
> +import 'package:base/page/sync.dart';
Согласен, ошибся, поправил

2021-11-19 07:06 UTC, artem-zaitsev approved these changes
Все отлично!

2021-11-19 09:13 UTC, merged